### ISSUE TITLE
missing license for this project

### ISSUE THREAD

**Issue by zeroheure** [mnurzia/rv#1]
Title says all. You didn't add a license. Is this project open-source ?

**Comment by mnurzia** [comment]
[MIT License in rv.h](https://github.com/mnurzia/rv/blob/main/rv.h#L81)

**Comment by vazhnov** [comment]
@mnurzia , could you please copy the license text into dedicated `LICENSE.txt` or something like this?

**Comment by mnurzia** [comment]
@vazhnov Done!

**Comment by vazhnov** [comment]
Great! Thank you very much!
